name: coralogix-aws-shipper tests
on:
  pull_request: 
    branches:
      - master

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
  
      - name: Install dependencies
        run: |
          pip install cfn-lint
          
        # validate the template file 
      - name: Run cfn-lint
        run: |
          error=$(cfn-lint --template template.yaml --region us-east-1 --ignore-checks W 2>&1)
          exit_code=$?
          if [ $exit_code -eq 0 ]; then
            echo "[INFO] no syntax error in the template"
          else
            echo "[ERROR] please fix the template file"
            echo "$error"
            exit 1
          fi

      
      # - name: install rust toolchain
      #   uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: stable
      #     override: true
      #     components: rustfmt, clippy
