name: coralogix-aws-shipper tests
on:
  pull_request: 
    branches:
      - master

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
  
      - name: Install dependencies
        run: |
          pip install cfn-lint
  
      - name: Run cfn-lint
        run: |
          cfn-lint --template template.yaml --ignore-checks W 2> cfn-lint-error.log || true
      
      - name: Display cfn-lint errors
        run: |
          if [[ $(cat cfn-lint-error.log) == "" ]]; then
            echo "no error"
            cat cfn-lint-error.log
          else
            echo "error"
          fi
      
      # - name: install rust toolchain
      #   uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: stable
      #     override: true
      #     components: rustfmt, clippy
