name: coralogix-aws-shipper tests
on:
  pull_request: 
    branches:
      - master

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
  
      - name: Install dependencies
        run: |
          pip install cfn-lint
          
        # validate the template file 
      - name: Run cfn-lint
        run: |
          cfn-lint --template template.yaml --region us-east-1 --ignore-checks W 

      # - name: install rust toolchain
      #   uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: stable
      #     override: true
      #     components: rustfmt, clippy
